version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/ruby:2.7.1-node
    environment:
      BUNDLE_PATH: vendor/bundle

commands:
  sayhello:
    description: "Say Hello"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: echo Hello << parameters.to >>

jobs:
  build:
    executor: my-executor
    steps:
      - sayhello:
        to: Everyone
